#!/usr/bin/env python3
"""Validate catalog metadata and regenerate the bilingual README sections."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog" / "skills.json"
READMES = {"en": ROOT / "README.md", "pt": ROOT / "README.pt-BR.md"}
START = "<!-- CATALOG:START -->"
END = "<!-- CATALOG:END -->"
ID_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

CATEGORIES = [
    ("official", "Official collection", "Coleção oficial"),
    ("regenerative-core", "Regenerative core", "Núcleo regenerativo"),
    ("development", "Development", "Desenvolvimento"),
    ("data-research", "Data & research", "Dados e pesquisa"),
    ("design-media", "Design & media", "Design e mídia"),
    ("productivity-collaboration", "Productivity & collaboration", "Produtividade e colaboração"),
    ("security-quality", "Security & quality", "Segurança e qualidade"),
]
ALLOWED = {
    "kind": {"skill", "plugin", "collection"},
    "provenance": {"openai-catalog", "community", "regenerative-core"},
    "surface": {"chat", "work", "codex"},
    "category": {item[0] for item in CATEGORIES},
}
REQUIRED = {
    "id", "name", "kind", "publisher", "category", "summary_en",
    "summary_pt_br", "url", "provenance", "license", "surfaces", "checked_on",
}
SYSTEMIC_LENSES = ("human", "social", "knowledge", "resources", "ecology")
RESOURCE_TYPES = {"attention", "time", "money", "compute", "data", "materials", "energy", "water"}
SYSTEMIC_REVIEW_FIELDS = {
    "status", "lenses", "harm_check", "reinforcing_loop", "balancing_safeguard",
    "regenerative_seed", "resource_ledger", "plain_language",
}

LABELS = {
    "en": {
        "kind": {"skill": "Skill", "plugin": "Plugin", "collection": "Collection"},
        "provenance": {
            "openai-catalog": "OpenAI catalog",
            "community": "Community",
            "regenerative-core": "Regenerative core",
        },
        "surface": {"chat": "Chat", "work": "Work", "codex": "Codex"},
        "status": {"design-reviewed": "Design reviewed"},
        "lens": {
            "human": "human", "social": "social", "knowledge": "knowledge",
            "resources": "resources", "ecology": "ecology",
        },
        "lenses": "lenses",
        "license": "License",
        "generated": "Generated by scripts/catalog.py. Do not edit this block manually.",
    },
    "pt": {
        "kind": {"skill": "Skill", "plugin": "Plugin", "collection": "Coleção"},
        "provenance": {
            "openai-catalog": "Catálogo OpenAI",
            "community": "Comunidade",
            "regenerative-core": "Núcleo regenerativo",
        },
        "surface": {"chat": "Chat", "work": "Work", "codex": "Codex"},
        "status": {"design-reviewed": "Projeto revisado"},
        "lens": {
            "human": "humana", "social": "social", "knowledge": "conhecimento",
            "resources": "recursos", "ecology": "ecologia",
        },
        "lenses": "áreas",
        "license": "Licença",
        "generated": "Gerado por scripts/catalog.py. Não edite este bloco manualmente.",
    },
}


def load_catalog() -> dict:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def nonempty_string(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def validate_systemic_review(review: object, where: str) -> list[str]:
    errors: list[str] = []
    if not isinstance(review, dict):
        return [f"{where} must be an object"]

    missing = SYSTEMIC_REVIEW_FIELDS - review.keys()
    extra = review.keys() - SYSTEMIC_REVIEW_FIELDS
    if missing:
        errors.append(f"{where} missing: {', '.join(sorted(missing))}")
    if extra:
        errors.append(f"{where} unknown fields: {', '.join(sorted(extra))}")
    if missing:
        return errors

    if review["status"] != "design-reviewed":
        errors.append(f"{where}.status must be design-reviewed until field-evidence validation exists")

    lenses = review["lenses"]
    if not isinstance(lenses, dict) or not 3 <= len(lenses) <= 5:
        errors.append(f"{where}.lenses must contain three to five lens objects")
    else:
        unknown_lenses = set(lenses) - set(SYSTEMIC_LENSES)
        if unknown_lenses:
            names = ", ".join(sorted(str(item) for item in unknown_lenses))
            errors.append(f"{where}.lenses contains invalid lenses: {names}")
        for lens, evidence in lenses.items():
            lens_where = f"{where}.lenses.{lens}"
            if not isinstance(evidence, dict) or set(evidence) != {"mechanism", "indicator"}:
                errors.append(f"{lens_where} must contain only mechanism and indicator")
                continue
            if not nonempty_string(evidence["mechanism"]):
                errors.append(f"{lens_where}.mechanism must be a non-empty string")
            if not nonempty_string(evidence["indicator"]):
                errors.append(f"{lens_where}.indicator must be a non-empty string")

    for field in ("harm_check", "reinforcing_loop", "balancing_safeguard", "regenerative_seed"):
        if not nonempty_string(review[field]):
            errors.append(f"{where}.{field} must be a non-empty string")

    ledger = review["resource_ledger"]
    ledger_fields = {"tracked", "baseline_comparison", "restoration"}
    if not isinstance(ledger, dict) or set(ledger) != ledger_fields:
        errors.append(f"{where}.resource_ledger must contain tracked, baseline_comparison, and restoration")
    else:
        tracked = ledger["tracked"]
        if not isinstance(tracked, list) or not tracked or not all(isinstance(item, str) for item in tracked):
            errors.append(f"{where}.resource_ledger.tracked must be a non-empty array of strings")
        elif len(tracked) != len(set(tracked)):
            errors.append(f"{where}.resource_ledger.tracked must be a non-empty unique array")
        elif set(tracked) - RESOURCE_TYPES:
            errors.append(f"{where}.resource_ledger.tracked contains an invalid resource type")
        for field in ("baseline_comparison", "restoration"):
            if not nonempty_string(ledger[field]):
                errors.append(f"{where}.resource_ledger.{field} must be a non-empty string")

    language = review["plain_language"]
    language_fields = {"summary_first", "technical_layer", "comprehension_check"}
    if not isinstance(language, dict) or set(language) != language_fields:
        errors.append(f"{where}.plain_language must contain summary_first, technical_layer, and comprehension_check")
    else:
        if language["summary_first"] is not True or language["technical_layer"] is not True:
            errors.append(f"{where}.plain_language must require both summary and technical layers")
        if not nonempty_string(language["comprehension_check"]):
            errors.append(f"{where}.plain_language.comprehension_check must be a non-empty string")
    return errors


def validate_catalog(data: dict) -> list[str]:
    errors: list[str] = []
    if data.get("schema_version") != 2:
        errors.append("schema_version must be 2")
    entries = data.get("entries")
    if not isinstance(entries, list) or not entries:
        return errors + ["entries must be a non-empty array"]

    seen_ids: set[str] = set()
    seen_urls: set[str] = set()
    core_ids: set[str] = set()
    core_lenses: set[str] = set()
    ecology_entries = 0
    for index, entry in enumerate(entries):
        where = f"entries[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{where} must be an object")
            continue
        missing = REQUIRED - entry.keys()
        extra = entry.keys() - (REQUIRED | {"systemic_review"})
        if missing:
            errors.append(f"{where} missing: {', '.join(sorted(missing))}")
        if extra:
            errors.append(f"{where} unknown fields: {', '.join(sorted(extra))}")
        if missing:
            continue

        entry_id = entry["id"]
        if not isinstance(entry_id, str) or not ID_RE.fullmatch(entry_id):
            errors.append(f"{where}.id must use lowercase letters, digits, and hyphens")
        else:
            if entry_id in seen_ids:
                errors.append(f"duplicate id: {entry_id}")
            seen_ids.add(entry_id)

        for field in ("name", "publisher", "summary_en", "summary_pt_br", "license"):
            if not isinstance(entry[field], str) or not entry[field].strip():
                errors.append(f"{where}.{field} must be a non-empty string")
        if str(entry["license"]).casefold() == "unspecified":
            errors.append(f"{where}.license may not be Unspecified")
        if not isinstance(entry["kind"], str) or entry["kind"] not in ALLOWED["kind"]:
            errors.append(f"{where}.kind is invalid")
        if not isinstance(entry["provenance"], str) or entry["provenance"] not in ALLOWED["provenance"]:
            errors.append(f"{where}.provenance is invalid")
        if not isinstance(entry["category"], str) or entry["category"] not in ALLOWED["category"]:
            errors.append(f"{where}.category is invalid")

        surfaces = entry["surfaces"]
        if not isinstance(surfaces, list) or not surfaces or not all(isinstance(item, str) for item in surfaces):
            errors.append(f"{where}.surfaces must be a non-empty array of strings")
        elif len(surfaces) != len(set(surfaces)):
            errors.append(f"{where}.surfaces must be a non-empty unique array")
        elif set(surfaces) - ALLOWED["surface"]:
            errors.append(f"{where}.surfaces contains an invalid value")

        url = entry["url"]
        parsed = urlparse(url) if isinstance(url, str) else None
        if not parsed or parsed.scheme != "https" or not parsed.netloc:
            errors.append(f"{where}.url must be an absolute HTTPS URL")
        else:
            if url in seen_urls:
                errors.append(f"duplicate url: {url}")
            seen_urls.add(url)
        try:
            date.fromisoformat(entry["checked_on"])
        except (TypeError, ValueError):
            errors.append(f"{where}.checked_on must be YYYY-MM-DD")

        is_core = entry["category"] == "regenerative-core" or entry["provenance"] == "regenerative-core"
        if is_core and not (
            entry["category"] == "regenerative-core" and entry["provenance"] == "regenerative-core"
        ):
            errors.append(f"{where} must use regenerative-core for both category and provenance")
        review = entry.get("systemic_review")
        if is_core:
            if isinstance(entry_id, str):
                core_ids.add(entry_id)
            errors.extend(validate_systemic_review(review, f"{where}.systemic_review"))
            if isinstance(review, dict) and isinstance(review.get("lenses"), dict):
                lens_names = set(review["lenses"]) & set(SYSTEMIC_LENSES)
                core_lenses.update(lens_names)
                ecology_entries += int("ecology" in lens_names)
            if isinstance(entry_id, str):
                canonical = ROOT / "skills" / entry_id / "SKILL.md"
                featured = ROOT / "skills" / "featured" / entry_id / "SKILL.md"
                if not canonical.is_file() and not featured.is_file():
                    errors.append(
                        f"{where} has no bundled skills/{entry_id}/SKILL.md "
                        f"or skills/featured/{entry_id}/SKILL.md"
                    )
        elif review is not None:
            errors.append(f"{where}.systemic_review is reserved for regenerative-core entries")

    bundled_core_ids = {path.parent.name for path in ROOT.glob("skills/*/SKILL.md")}
    bundled_core_ids |= {path.parent.name for path in ROOT.glob("skills/featured/*/SKILL.md")}
    if core_ids != bundled_core_ids:
        missing_catalog = bundled_core_ids - core_ids
        missing_source = core_ids - bundled_core_ids
        if missing_catalog:
            errors.append(f"bundled core skills missing from catalog: {', '.join(sorted(missing_catalog))}")
        if missing_source:
            errors.append(f"catalog core entries missing bundled source: {', '.join(sorted(missing_source))}")
    if core_ids and core_lenses != set(SYSTEMIC_LENSES):
        errors.append("regenerative core portfolio must cover all five systemic lenses")
    if core_ids and ecology_entries < 2:
        errors.append("at least two regenerative core entries must include the ecology lens")
    return errors


def validate_repo_skills() -> list[str]:
    errors: list[str] = []
    paths = (
        sorted(ROOT.glob(".agents/skills/*/SKILL.md"))
        + sorted(ROOT.glob("skills/*/SKILL.md"))
        + sorted(ROOT.glob("skills/featured/*/SKILL.md"))
    )
    for path in paths:
        text = path.read_text(encoding="utf-8")
        if "TODO" in text or not text.startswith("---\n"):
            errors.append(f"{path.relative_to(ROOT)} has unfinished or invalid frontmatter")
            continue
        end = text.find("\n---\n", 4)
        frontmatter = text[4:end] if end >= 0 else ""
        values = {}
        for line in frontmatter.splitlines():
            if ":" in line:
                key, value = line.split(":", 1)
                values[key.strip()] = value.strip().strip('"')
        name = values.get("name", "")
        description = values.get("description", "")
        if name != path.parent.name or not ID_RE.fullmatch(name):
            errors.append(f"{path.relative_to(ROOT)} name must match its folder")
        if len(description) < 40:
            errors.append(f"{path.relative_to(ROOT)} description is not discriminating")
        ui = path.parent / "agents" / "openai.yaml"
        if path.parent.parent == ROOT / "skills" and not ui.is_file():
            errors.append(f"{ui.relative_to(ROOT)} is required for regenerative core skills")
        if ui.exists():
            ui_text = ui.read_text(encoding="utf-8")
            if "default_prompt:" not in ui_text or f"${name}" not in ui_text:
                errors.append(f"{ui.relative_to(ROOT)} default prompt must mention ${name}")
    return errors


def render(entries: list[dict], language: str) -> str:
    labels = LABELS[language]
    lines: list[str] = []
    for category, title_en, title_pt in CATEGORIES:
        selected = sorted((e for e in entries if e["category"] == category), key=lambda e: e["name"].casefold())
        if not selected:
            continue
        lines.extend([f"### {title_en if language == 'en' else title_pt}", ""])
        for entry in selected:
            summary = entry["summary_en"] if language == "en" else entry["summary_pt_br"]
            tags = [labels["kind"][entry["kind"]], labels["provenance"][entry["provenance"]]]
            review = entry.get("systemic_review")
            if review:
                tags.append(labels["status"][review["status"]])
                lens_names = ", ".join(labels["lens"][lens] for lens in review["lenses"])
                tags.append(f"{len(review['lenses'])}/5 {labels['lenses']}: {lens_names}")
            tags.extend(labels["surface"][surface] for surface in entry["surfaces"])
            tags.append(f"{labels['license']}: {entry['license']}")
            metadata = " · ".join(f"`{tag}`" for tag in tags)
            lines.append(
                f"- [**{entry['name']}**]({entry['url']}) — {summary} "
                f"{metadata} · {entry['publisher']} · {entry['checked_on']}"
            )
        lines.append("")
    return "\n".join(lines).rstrip()


def generated_readme(current: str, entries: list[dict], language: str) -> str:
    if current.count(START) != 1 or current.count(END) != 1:
        raise ValueError("README must contain exactly one catalog marker pair")
    comment = f"<!-- {LABELS[language]['generated']} -->"
    block = f"{START}\n{comment}\n\n{render(entries, language)}\n{END}"
    return re.sub(re.escape(START) + r".*?" + re.escape(END), block, current, flags=re.S)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    try:
        data = load_catalog()
    except (OSError, json.JSONDecodeError) as exc:
        print(f"catalog error: {exc}", file=sys.stderr)
        return 1
    errors = validate_catalog(data) + validate_repo_skills()
    if errors:
        print("Validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    for language, path in READMES.items():
        current = path.read_text(encoding="utf-8")
        try:
            expected = generated_readme(current, data["entries"], language)
        except ValueError as exc:
            errors.append(f"{path.name}: {exc}")
            continue
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif current != expected:
            errors.append(f"{path.name} catalog block is stale; run --write")

    if errors:
        print("Validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"Catalog valid: {len(data['entries'])} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
